name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release

    concurrency:
      group: github-release-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v3

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}

  publish-npm:
    name: Publish to NPM

    concurrency:
      group: npm-release-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: npm
      url: https://www.npmjs.com/package/kutt

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build:hybrid

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Packages

    concurrency:
      group: gpr-release-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: gpr
      url: https://github.com/${{ github.repository }}/packages

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@ardalanamini'

      - run: sed -i 's/"name":\ "kutt"/"name":\ "@ardalanamini\/kutt"/g' package.json package-lock.json

      - run: npm ci

      - run: npm run build:hybrid

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
