# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test

    timeout-minutes: 15

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 15
          - 16
          - 17

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ matrix.os }}-${{ github.ref_name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.os }}-${{ github.ref_name }}-${{ matrix.node-version }}
            node-modules-${{ matrix.os }}-master-${{ matrix.node-version }}
            node-modules-${{ matrix.os }}-${{ github.ref_name }}-
            node-modules-${{ matrix.os }}-master-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i --no-fund

      - name: Check code styles
        run: npm run lint

      - name: Build for CommonJS
        run: npm run build

      - name: Build for ECMAScript
        run: npm run build:es
